### PR TITLE
[Message Center] Fixes

### LINKED ISSUE #38: [Fetch] Error in a modal displayed "under" the modal
Hello,

The response status of the server is well used to display an error :+1: , but in the case of a modal, the error "toaster" is displayed under the modal, in the list component.

"focus-application": "3.0.0-rc16"

### PR DESCRIPTION
**Pull request by TomGallon**
## Fixes
- message types
- message translation
- message over modal. fixes #38

### CODE REVIEW

File: src/messages/messages-component.js [hunk 1]
```diff
@@ -1,49 +1,66 @@
...
-  }
-  componentWillUnmount(){
-    clearTimeout(this.timeoutId);
-  }
-  render(){
-    const {MessageComponent,i18nTranslation, ...otherMessageProps} = this.props;
-    return <MessageComponent  i18nTranslation={i18nTranslation}  {...otherMessageProps} />
-  }
-}
+function Message({messageId, content, title, deleteMessage, i18nTranslation}){
```
Comment (Ephrame) [inline src/messages/messages-component.js]: i18nTranslation to be delete
